name: Update Requirements

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update requirements.txt
        uses: timmypidashev/auto-pipreqs-cpy@master
        with:
          REQUIREMENT_PATH: path/to/requirements.txt  # Path to your requirements.txt file
          # Optional: If you want to ignore specific paths
          IGNORE_PATH: submodules  # Replace 'submodules' with your desired ignore path, or remove this line if not needed
