name: Update Requirements

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt  # Install existing dependencies

      - name: Generate updated requirements.txt
        run: |
          python -m pip freeze > requirements.txt  # Generate updated requirements.txt
